import type { Metadata } from "next";
import "../dist/output.css";
// import "./globals.css";
import { Inter } from "next/font/google";
import { cn } from "ui";
import LocalFont from "next/font/local";
import Background from "@/components/background";
import { ThemeProvider } from "../src/components/theme-provider";

const inter = Inter({ subsets: ["latin"], weight: "500" });
const calSans = LocalFont({
  src: "../src/public/fonts/CalSans-SemiBold.ttf",
  variable: "--font-calsans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.className,
          `${inter.className} ${calSans.variable}`,
        )}
      >
        <Background>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
            enableSystem
          >
            <>
              {/*<AppHeader />*/}
              {children}
            </>
          </ThemeProvider>
        </Background>
      </body>
    </html>
  );
}
